#!/bin/bash
# Build /opt/dupli1/.env (+ the JWT signing key file) from the age-encrypted
# Secrets Manager backup. Prints key names only, never values.
#
#   deploy/venus/make-env.sh <backup-dir> <age-identity-file>
#
# Carried over from AWS: JWT secret + RS256 key (existing sessions stay valid),
# service-account credentials, Nano Pay, Telegram. Newly generated: Postgres
# superuser, app role, S3 (SeaweedFS) key. Re-running keeps generated values.
set -euo pipefail
BACKUP=${1:?backup dir, e.g. ~/backups/dupli1-2026-09-26}
IDENTITY=${2:?age identity file}
OUT=${DUPLI1_HOME:-/opt/dupli1}

sudo install -d -m 700 -o "$(id -u)" -g "$(id -g)" "$OUT" "$OUT/secrets"
umask 077

python3 - "$BACKUP" "$IDENTITY" "$OUT" <<'EOF'
import json, os, secrets, subprocess, sys
backup, identity, out = sys.argv[1:]

def secret(name):
    path = f"{backup}/secrets/dupli1_production_{name}.json.age"
    raw = subprocess.run(["age", "-d", "-i", identity, path], check=True, capture_output=True).stdout
    s = json.loads(raw)["SecretString"]
    try:
        v = json.loads(s)
        return v if isinstance(v, dict) else s
    except ValueError:
        return s

env_path = f"{out}/.env"
old = {}
if os.path.exists(env_path):
    for line in open(env_path):
        if "=" in line and not line.startswith("#"):
            k, v = line.rstrip("\n").split("=", 1)
            old[k] = v[1:-1] if v.startswith("'") else v

def generated(k):
    return old.get(k) or secrets.token_urlsafe(32)

auth_td = json.load(open(f"{backup}/config/taskdef-dupli1-auth_7.json"))["taskDefinition"]
auth_env = {e["name"]: e["value"] for c in auth_td["containerDefinitions"] for e in c.get("environment", [])}
order_acct, web_acct = secret("order-service-account"), secret("web-service-account")
nano, telegram = secret("nano-payment"), secret("telegram")

env = {
    "PG_SUPERUSER_PASSWORD": generated("PG_SUPERUSER_PASSWORD"),
    "DB_APP_PASSWORD": generated("DB_APP_PASSWORD"),
    "S3_SECRET_KEY": generated("S3_SECRET_KEY"),
    "JWT_SECRET": secret("jwt-secret"),
    "AUTH_WEB_SERVICE_PASSWORD": auth_env["DUPLI1_WEB_SERVICE_PASSWORD"],
    "DUPLI1_ORDER_SERVICE_EMAIL": order_acct["DUPLI1_ORDER_SERVICE_EMAIL"],
    "DUPLI1_ORDER_SERVICE_PASSWORD": order_acct["DUPLI1_ORDER_SERVICE_PASSWORD"],
    "WEB_SERVICE_EMAIL": web_acct["DUPLI1_WEB_SERVICE_EMAIL"],
    "WEB_SERVICE_PASSWORD": web_acct["DUPLI1_WEB_SERVICE_PASSWORD"],
    **{k: nano[k] for k in ("NANO_API_KEY", "NANO_LOGIN_ID", "NANO_SHOPCODE", "NANO_VER")},
    # Live Telegram values are parked under *_AT_CUTOVER; cutover.sh moves them
    # into TELEGRAM_* once the AWS notification service is stopped.
    "TELEGRAM_BOT_TOKEN": old.get("TELEGRAM_BOT_TOKEN", ""),
    "TELEGRAM_ORDER_CHAT_ID": old.get("TELEGRAM_ORDER_CHAT_ID", ""),
    "TELEGRAM_PRODUCT_CHAT_ID": old.get("TELEGRAM_PRODUCT_CHAT_ID", ""),
    **{f"{k}_AT_CUTOVER": telegram[k] for k in ("TELEGRAM_BOT_TOKEN", "TELEGRAM_ORDER_CHAT_ID", "TELEGRAM_PRODUCT_CHAT_ID")},
    "CLOUDFLARE_TUNNEL_TOKEN": old.get("CLOUDFLARE_TUNNEL_TOKEN", ""),
}
for k, v in env.items():
    if not isinstance(v, str) or "'" in v or "\n" in v:
        sys.exit(f"{k}: value can't be written as a single-quoted .env line")
with open(env_path + ".tmp", "w") as f:
    f.write("# Generated by deploy/venus/make-env.sh. Secret — never commit.\n")
    for k, v in env.items():
        f.write(f"{k}='{v}'\n")
os.replace(env_path + ".tmp", env_path)

pem = secret("jwt-private-key")
if not isinstance(pem, str) or "PRIVATE KEY" not in pem:
    sys.exit("jwt-private-key: not a PEM")
with open(f"{out}/secrets/jwt_private_key.pem", "w") as f:
    f.write(pem if pem.endswith("\n") else pem + "\n")
# auth's container user must be able to read the mounted key.
os.chmod(f"{out}/secrets/jwt_private_key.pem", 0o644)
os.chmod(f"{out}/secrets", 0o711)

print(f"wrote {env_path}: " + ", ".join(env))
print(f"wrote {out}/secrets/jwt_private_key.pem")
EOF
