upstream schick_auth {
    server schick-auth:8080;
}

upstream schick_product {
    server schick-product:8080;
}

upstream schick_inventory {
    server schick-inventory:8080;
}

upstream schick_order {
    server schick-order:8080;
}

server {
    listen 80;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /auth/ {
        proxy_pass http://schick_auth/;
    }

    location /product/ {
        proxy_pass http://schick_product/;
    }

    location /inventory/ {
        proxy_pass http://schick_inventory/;
    }

    location /order/ {
        proxy_pass http://schick_order/;
    }
}
