#!/usr/bin/env bash
set -euo pipefail

# Pull Dupli1 production RDS connection strings from AWS Secrets Manager
# and write a local .env.rds file for docker compose or direct service runs.
#
# Prerequisites:
#   - AWS CLI configured (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY or a profile)
#   - VPN connected when RDS is in a private subnet
#
# Usage:
#   bash infra/scripts/fetch-rds-env.sh
#   docker compose -f docker-compose.yml -f docker-compose.rds.yml --env-file .env.rds up

AWS_REGION="${AWS_REGION:-us-east-1}"
OUTPUT_FILE="${OUTPUT_FILE:-.env.rds}"
JWT_SECRET="${JWT_SECRET:-dev-secret-change-in-production}"
OWNER_EMAIL="${OWNER_EMAIL:-admin@dupli1.com}"
OWNER_PASSWORD="${OWNER_PASSWORD:-password}"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "missing required command: $1" >&2
    exit 1
  }
}

require_cmd aws
require_cmd jq

SECRET_ARN="${DB_SECRET_ARN:-$(aws secretsmanager list-secrets \
  --region "$AWS_REGION" \
  --query "SecretList[?contains(Name, 'dupli1/production/database')].ARN | [0]" \
  --output text)}"

if [[ -z "$SECRET_ARN" || "$SECRET_ARN" == "None" ]]; then
  echo "could not resolve DB secret ARN; set DB_SECRET_ARN" >&2
  exit 1
fi

SECRET_JSON="$(aws secretsmanager get-secret-value \
  --region "$AWS_REGION" \
  --secret-id "$SECRET_ARN" \
  --query SecretString \
  --output text)"

AUTH_DB_URL="$(echo "$SECRET_JSON" | jq -r .auth_db_url)"
PRODUCT_DB_URL="$(echo "$SECRET_JSON" | jq -r .product_db_url)"
RDS_HOST="$(echo "$SECRET_JSON" | jq -r .host)"

cat >"$OUTPUT_FILE" <<EOF
# Generated by infra/scripts/fetch-rds-env.sh — do not commit
# RDS host: ${RDS_HOST}
# Connect via VPN before starting services against production RDS.

JWT_SECRET=${JWT_SECRET}

DB_URL=${AUTH_DB_URL}
OWNER_EMAIL=${OWNER_EMAIL}
OWNER_PASSWORD=${OWNER_PASSWORD}

DUPLI1_PRODUCT_DB=${PRODUCT_DB_URL}
S3_ENDPOINT=http://localhost:9000
S3_ACCESS_KEY=dupli1
S3_SECRET_KEY=dupli1_dev
S3_BUCKET=product-images

MINIO_ACCESS_KEY=dupli1
MINIO_SECRET_KEY=dupli1_dev
EOF

chmod 600 "$OUTPUT_FILE"
echo "Wrote ${OUTPUT_FILE}"
echo "Start with: docker compose -f docker-compose.yml -f docker-compose.rds.yml --env-file ${OUTPUT_FILE} up --build"
